version: 2

registries:
  contribsys:
    type: rubygems-server
    url: https://enterprise.contribsys.com/
    token: ${{ secrets.BUNDLE_ENTERPRISE__CONTRIBSYS__COM }}

updates:
  - package-ecosystem: bundler
    directory: /
    registries:
      - contribsys
    schedule:
      interval: daily
    # appears to be required for this package manager to work at all
    insecure-external-code-execution: allow

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    ignore:
      # leave this for renovate to handle, since renovate is already
      # handling the other parts of upgrading ruby (see renovate.json5)
      - dependency-name: ruby

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
