default: &default
  pool: <%= ENV["DATABASE_CONNECTION_POOL_SIZE"].presence || 5 %>

development:
  <<: *default
  adapter: postgresql
  database: lightward_ai_development
  username: lightward_ai

test: &test
  <<: *default
  adapter: postgresql
  database: lightward_ai_test
  username: lightward_ai

production:
  <<: *default
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
