name: Fly secrets

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      stage_only:
        required: false
        type: boolean
        default: true

jobs:
  deploy:
    name: Fly secrets
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Initialize Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set secrets
        run: |
          stage_flag=""
          if [ "${{ inputs.stage_only }}" = "true" ]; then
            stage_flag="--stage"
          fi
          flyctl secrets set \
            $stage_flag \
            --app ${{ vars.FLY_APP_NAME }} \
            ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_API_KEY }}" \
            ANTHROPIC_MODEL="${{ vars.ANTHROPIC_MODEL }}" \
            DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            HOST="${{ vars.HOST }}" \
            LOG_LEVEL="${{ vars.LOG_LEVEL }}" \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
