name: Fly secrets

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      stage_only:
        required: false
        type: boolean
        default: true

jobs:
  deploy:
    name: Fly secrets
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Initialize Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set secrets
        run: |
          stage_flag=""
          if [ "${{ inputs.stage_only }}" = "true" ]; then
            stage_flag="--stage"
          fi
          flyctl secrets set \
            $stage_flag \
            --app ${{ vars.FLY_APP_NAME }} \
            ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_API_KEY }}" \
            DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            GOOD_JOB_PASSWORD="${{ secrets.GOOD_JOB_PASSWORD }}" \
            GOOD_JOB_PRESERVE_JOB_RECORDS="${{ vars.GOOD_JOB_PRESERVE_JOB_RECORDS }}" \
            GOOD_JOB_USERNAME="${{ vars.GOOD_JOB_USERNAME }}" \
            GOOGLE_SIGN_IN_CLIENT_ID="${{ vars.GOOGLE_SIGN_IN_CLIENT_ID }}" \
            GOOGLE_SIGN_IN_CLIENT_SECRET="${{ secrets.GOOGLE_SIGN_IN_CLIENT_SECRET }}" \
            HELPSCOUT_APP_ID="${{ vars.HELPSCOUT_APP_ID }}" \
            HELPSCOUT_APP_SECRET="${{ secrets.HELPSCOUT_APP_SECRET }}" \
            HELPSCOUT_USER_ID="${{ vars.HELPSCOUT_USER_ID }}" \
            HELPSCOUT_WEBHOOK_SECRET_KEY="${{ secrets.HELPSCOUT_WEBHOOK_SECRET_KEY }}" \
            HOST="${{ vars.HOST }}" \
            LOG_LEVEL="${{ vars.LOG_LEVEL }}" \
            NEW_RELIC_ACCOUNT_ID="${{ vars.NEW_RELIC_ACCOUNT_ID }}" \
            NEW_RELIC_APP_NAME="${{ vars.NEW_RELIC_APP_NAME }}" \
            NEW_RELIC_LICENSE_KEY="${{ secrets.NEW_RELIC_LICENSE_KEY }}" \
            ROLLBAR_ACCESS_TOKEN="${{ secrets.ROLLBAR_ACCESS_TOKEN }}" \
            ROLLBAR_ENV="${{ vars.ROLLBAR_ENV }}" \
            ROLLBAR_POST_CLIENT_ITEM_ACCESS_TOKEN="${{ secrets.ROLLBAR_POST_CLIENT_ITEM_ACCESS_TOKEN }}" \
            SLACK_API_TOKEN="${{ secrets.SLACK_API_TOKEN }}" \
            STRIPE_PRODUCT_ID="${{ vars.STRIPE_PRODUCT_ID }}" \
            STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
            STRIPE_WEBHOOK_SECRET="${{ secrets.STRIPE_WEBHOOK_SECRET }}" \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
