name: Fly secrets

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      stage_only:
        required: false
        type: boolean
        default: true

permissions: {}

jobs:
  deploy:
    name: Fly secrets
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Initialize Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set secrets
        run: |
          stage_flag=""
          if [ "${{ inputs.stage_only }}" = "true" ]; then
            stage_flag="--stage"
          fi
          flyctl secrets set \
            $stage_flag \
            --app ${{ vars.FLY_APP_NAME }} \
            ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_API_KEY }}" \
            DISABLE_TOKEN_LIMIT_AUTHORIZATION="${{ secrets.DISABLE_TOKEN_LIMIT_AUTHORIZATION }}" \
            HOST="${{ vars.HOST }}" \
            LOG_LEVEL="${{ vars.LOG_LEVEL }}" \
            NEW_RELIC_APP_NAME="${{ vars.NEW_RELIC_APP_NAME }}" \
            NEW_RELIC_INGEST_KEY="${{ secrets.NEW_RELIC_INGEST_KEY }}" \
            ROLLBAR_ACCESS_TOKEN="${{ secrets.ROLLBAR_ACCESS_TOKEN }}" \
            ROLLBAR_ENV="${{ vars.ROLLBAR_ENV }}" \
            ROLLBAR_POST_CLIENT_ITEM_ACCESS_TOKEN="${{ secrets.ROLLBAR_POST_CLIENT_ITEM_ACCESS_TOKEN }}" \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
