name: Update git submodules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily midnight utc

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules
        run: |
          git submodule update --remote --recursive

      - name: Check for changes
        run: |
          if git status --porcelain | grep .; then
            echo "Submodules updated"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "Update submodules"
          else
            echo "No submodule updates"
            exit 0
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-submodules
          commit-message: Update submodules
          title: Update submodules
          body: |
            This pull request updates the submodules to their latest commits.
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
