name: Main

on:
  # daily
  schedule:
    - cron: 0 0 * * *

  # on push to main
  push:
    branches:
      - main

permissions: {}

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      sha: ${{ github.sha }}
