name: Test

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string

jobs:
  build:
    name: Build
    secrets: inherit
    uses: lightward/.github-private/.github/workflows/fly-build.yml@main
    with:
      commitish: ${{ inputs.sha }}
      environment: staging

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ inputs.sha }}
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint Ruby files
        run: bin/rubocop --parallel --only-recognized-file-types --extra-details --format github --fail-level info

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ inputs.sha }}
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman --quiet --confidence-level 1 --format github

  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    env:
      DATABASE_URL: 'postgres://rails:password@localhost:5432/rails_test'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ inputs.sha }}
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run rspec tests
        run: bin/rspec --format RSpec::Github::Formatter --format documentation --force-color
