name: Test

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string

jobs:
  build:
    name: Build
    secrets: inherit
    uses: lightward/.github-private/.github/workflows/fly-build.yml@main
    with:
      commitish: ${{ inputs.sha }}
      environment: lightward.ai

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint Ruby files
        run: bin/rubocop --parallel --only-recognized-file-types --extra-details --format github --fail-level info

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman --quiet --confidence-level 1 --format github

  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run rspec tests
        run: bin/rspec --format RSpec::Github::Formatter --format documentation --force-color
