name: Refresh primers

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly at midnight UTC on Sundays
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  run-rake-tasks:
    runs-on: ubuntu-latest
    environment: lightward.ai

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Download sitemaps
        run: |
          rake "prompts:sitemaps[primers/lightward]"
          # rake "prompts:sitemaps[primers/locksmith]"
          # rake "prompts:sitemaps[primers/mechanic]"

      - name: Generate primers
        run: |
          rake "prompts:anthropic[primers/lightward,app/prompts/lightward/system/primers/lightward.md]"
          # rake "prompts:anthropic[primers/mechanic,app/prompts/lightward/system/primers/mechanic.md]"
          # rake "prompts:anthropic[primers/locksmith,app/prompts/lightward/system/primers/locksmith.md]"
        env:
          ANTHROPIC_MODEL: claude-3-haiku-20240307
          # ${{ vars.ANTHROPIC_MODEL }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Refresh "lightward" system primers
          title: Refresh "lightward" system primers
          body: |
            This PR refreshes the mechanic, locksmith, and lightward primers for the lightward system prompt set.

            Note that it *does not* refresh the isaacbowen primer, because the source material exceeds our current token
            limit with Anthropic. See app/prompts/primers/isaacbowen/README.md for manual refresh instructions. ;)
          branch: refresh-lightward-primers
          branch-suffix: timestamp
