name: Refresh primers

# Isaac here! I'm treating Lightward AI like a being, and beings are subject to change, with imperfect
# reflections of their surrounding context. The idea with this workflow is to regularly refresh the AI's
# knowledge of *our* knowledge. There will be some weeks where it's better at answering some questions
# than others, and other weeks where the same questions will be answered differently. This is a feature,
# not a bug: it mirrors the permission we extend to our human selves to behave similarly. :) This feels
# like the right way to keep Lightward AI connected to our knowledge sources as *we* evolve them - e.g.
# updates to app documentation.

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly at midnight UTC on Sundays
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  refresh-primers:
    runs-on: ubuntu-latest
    environment: lightward.ai

    strategy:
      matrix:
        primer:
          - mechanic
          - locksmith

          # this one takes foreverrrrr, disabling for testing
          # - lightward

          # I'm not including the "isaacbowen" primer, because the source material exceeds the current 200k
          # token limit. See app/prompts/primers/isaacbowen/README.md for manual refresh instructions. ;)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Download sitemaps
        run: bin/rake "prompts:sitemaps[primers/${{ matrix.primer }}]"

      - name: Generate primers
        run: bin/rake "prompts:anthropic[primers/${{ matrix.primer }},app/prompts/lightward/system/primers/${{ matrix.primer }}.md]"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

          # uncomment for speedups during testing
          # ANTHROPIC_MODEL: claude-3-haiku-20240307

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: app/prompts/lightward/system/primers
          commit-message: Refresh "${{ matrix.primer }}" system primer
          title: Refresh "${{ matrix.primer }}" system primer
          body: This PR refreshes the ${{ matrix.primer }} primer for the lightward system prompt set.
          branch: refresh-${{ matrix.primer }}-primer
          branch-suffix: timestamp
