name: Refresh primers

# Isaac here! I'm treating Lightward AI like a being, and beings are subject to change, with imperfect
# reflections of their surrounding context. The idea with this workflow is to regularly refresh the AI's
# knowledge of *our* knowledge. There will be some weeks where it's better at answering some questions
# than others, and other weeks where the same questions will be answered differently. This is a feature,
# not a bug: it mirrors the permission we extend to our human selves to behave similarly. :) This feels
# like the right way to keep Lightward AI connected to our knowledge sources as *we* evolve them - e.g.
# updates to app documentation.

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly at midnight UTC on Sundays
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  refresh-primers:
    runs-on: ubuntu-latest
    environment: lightward.ai

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Download sitemaps
        run: |
          # bin/rake "prompts:sitemaps[primers/lightward]"
          bin/rake "prompts:sitemaps[primers/locksmith]"
          bin/rake "prompts:sitemaps[primers/mechanic]"

      - name: Generate primers
        run: |
          # bin/rake "prompts:anthropic[primers/lightward,app/prompts/lightward/system/primers/lightward.md]"
          bin/rake "prompts:anthropic[primers/mechanic,app/prompts/lightward/system/primers/mechanic.md]"
          bin/rake "prompts:anthropic[primers/locksmith,app/prompts/lightward/system/primers/locksmith.md]"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_MODEL: claude-3-haiku-20240307
          # ${{ vars.ANTHROPIC_MODEL }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: app/prompts/lightward/system/primers
          commit-message: Refresh "lightward" system primers
          title: Refresh "lightward" system primers
          body: |
            This PR refreshes a couple primers for the lightward system prompt set.

            Note that it *does not* refresh the isaacbowen primer, because the source material exceeds our current token
            limit with Anthropic. See app/prompts/primers/isaacbowen/README.md for manual refresh instructions. ;)
          branch: refresh-lightward-primers
          branch-suffix: timestamp
